[package]
name = "qssmonitor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = {version ="0.4.26", features = ["serde"]}
config = "0.13.3"
configgen-rs = "0.1.1"
home = "0.5.5"
serde = { version = "1.0.174", features = ["derive"] }
serde_with = {version = "3.2.0", features = ["chrono_0_4"]}
